# Generated by Django 3.2.7 on 2021-09-30 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='board',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='board',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('CLOSED', 'closed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(choices=[('admin', 'admin')], default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.board'),
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('IN PROGRESS', 'in progress'), ('CLOSED', 'closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(default='Test Task - Ignore', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
