# Generated by Django 3.2.7 on 2021-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
